name: giwifi_ua_switcher
description: GiWiFi 校园网一键认证工具（UA 设备类型切换 + 账号密码本地保存）
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true